name: Continuous Delivery
on:
  push:
    branches: 
      - main # ou qualquer outras branches que você deseja monitorar para implantações contínuas

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Simulando Continuous Delivery
        uses: actions/upload-artifact@v7
        with:
            name: projetozipado.zip
            path: |
              '**.py'
              README.md
